version: "3.9"

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}

services:
  web:
    image: node:18.15.0
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - 443:443
    volumes:
      - ./:/home/node/app
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    tty: true
    expose:
      - 443
    command: "npm run dev"
